### ISSUE TITLE
Ice not working on incoming calls

### ISSUE THREAD

**Issue by lazydev2** [BelledonneCommunications/linphone-sdk#413]
Hello.
I am trying to use linphone with enabled ice.
If i make a call from linphoen app, then ice attributes are present in SDP data.

But if the app received a call, it answers with no ICE attributes.
There is not much information in logs:
```
$ grep " ICE " 6698cf865e936_d1658f4107263b48f310
2024-07-18 11:16:49:406 [comm.preo.linphone/liblinphone] MESSAGE ICE state is IceStateNotActivated for stream#0 [audio] in state [Stopped]
2024-07-18 11:16:51:589 [comm.preo.linphone/liblinphone] MESSAGE Checking for ICE reINVITE
2024-07-18 11:16:51:598 [comm.preo.linphone/liblinphone] MESSAGE ICE state is IceStateNotActivated for stream#0 [audio] in state [Running]
$
```
(full logs available [here](https://www.linphone.org:444//tmp/6698cf865e936_d1658f4107263b48f310.gz))

So I need help to solve the prooblem.
I am not sure it is a bug, but there are no more suitable issue types.

linphone versions is 5.2, built manually from git commit 0206753d78847402b4ab0d0014337ada6e0a7b23

**Comment by lazydev2** [comment]
It is offtopic, but I cannot correctrly built the app of lates vrsion.
./gradlew assembleRelease gives no errors, however, if I try to install the app on smartphone, I am gettimg message "Appliation is not installed".

When I am trying to install to smartphone emulator, I am getting error:
```
The APK failed to install.
Error: INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl1367721440.tmp/base.apk: Failed to collect certificates from /data/app/vmdl1367721440.tmp/base.apk: Attempt to get length of null array
```

Gogle says it somehow connected to signing the app, but i still cannot figure out what to do.

for 5.2 it was enougth to generate a keystore and put it and file with its properties into app dir.
But now that is not working

**Comment by lazydev2** [comment]
> Hi @lazydev2,
> 
> There's been a fix for that in our SDK recently: https://gitlab.linphone.org/BC/public/linphone-sdk/-/commit/663b566f07083008f1ed0e672baaeee8edf2bda8 You should try it out.
> 
> Cheers,

And, by the way, is it possible so somehow backport the fix into stable release?

**Comment by lazydev2** [comment]
Could you please give more details how to use custom-build sdk?
I [think I] successfully bult the SDK using instructions in README.md, and in order to use it, I put 
> LinphoneSdkBuildDir=path_to_sdk/build-android

in ~/.gradle/gradle.properties AND in linphone-android_5.2/gradle.properties
(linphone-android_5.2 is the directory containing source files).

However, according to gradle, SDK from repository is still used:
```
linphone-android_5.2$ ANDROID_HOME=path_to_android_sdk ./gradlew assembleRelease

> Configure project :app
Git version: 5.2.5.1+0206753d7 (52005)
WARNING: BuildType(releaseWithCrashlytics): resValue 'bool/crashlytics_enabled' value is being replaced.

> Task :app:linphoneSdkSource
**Linphone SDK used is 5.3.73-pre.1+809988a8 from linphone.org maven repository**
```

what I did wrong and what I need to do to compile linphone-android with my custom-built sdk?

**Comment by Viish** [comment]
> Could you please give more details how to use custom-build sdk?

Fix has been made in master branch, which means the SDK built has a 5.40-alpha version number.
You need to change the implementation line in app/build.gradle so it requires a 5.4+ SDK instead of a 5.3+.
You should also edit the settings.gradle file and comment out our online maven repository to make sure it uses the local one, as it always pick the most recent SDK based on version number and that may not be the one you built.

**Comment by lazydev2** [comment]
Thanks for the reply, however, I still cannot do it :(

> You need to change the implementation line in app/build.gradle so it requires a 5.4+ SDK instead of a 5.3+.

I changed 
`implementation 'org.linphone:linphone-sdk-android:5.3+'`
to
`implementation 'org.linphone:linphone-sdk-android:5.4+'`

Is it correct?

> You should also edit the settings.gradle file and comment out our online maven repository to make sure it uses the local one, as it always pick the most recent SDK based on version number and that may not be the one you built.

I commented this section:
```
/*
maven {
    name "linphone.org maven repository"
    url "https://linphone.org/maven_repository"
    content {
        includeGroup "org.linphone"
    }
}
*/
```
Now my local sdk is used:
```
inphone-android_5.2$ ANDROID_HOME=<path to android sdk> ./gradlew assembleRelease

> Configure project :app
Git version: 5.2.5.1+0206753d7 (52005)
WARNING: BuildType(releaseWithCrashlytics): resValue 'bool/crashlytics_enabled' value is being replaced.

> Task :app:linphoneSdkSource
Linphone SDK used is 5.4.0-alpha.297+5459708b from local linphone-sdk maven repository
```

But compilation fails:
```
> Task :app:kaptReleaseKotlin
warning: ERROR: View field icon collides with a variable or import file://app/src/main/res/layout/settings_widget_basic.xml Line:29
warning: ERROR: View field dialogMessage collides with a variable or import file://app/src/main/res/layout/voip_dialog_info.xml Line:33

> Task :app:compileReleaseKotlin
e: file://<...>/linphone-android_5.2/app/src/main/java/org/linphone/activities/voip/viewmodels/ConferenceViewModel.kt:562:13 Type mismatch: inferred type is Address? but Address was expected
e: file://<...>/linphone-android_5.2/app/src/main/java/org/linphone/activities/voip/viewmodels/ConferenceViewModel.kt:672:13 Type mismatch: inferred type is Address? but Address was expected
e: file://<...>/linphone-android_5.2/app/src/main/java/org/linphone/utils/LinphoneUtils.kt:97:21 Type mismatch: inferred type is Address? but Address was expected

> Task :app:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

(I am trying to use fresh sdk with release 5.2, is that setup even can be built correctly?).
I am not a java/kotlin programmer, so I need help again.

**Comment by Viish** [comment]
Yes there have been a few API changes between 5.3 and 5.4 SDK and release/5.2 branch isn't made for it.

You can switch to master branch commit ID 4624d2698d2051662350e2a857aac43d6fe27d01 that is basically the same as release/5.2 but will build with 5.4 SDK.

**Comment by lazydev2** [comment]
No success :(
```
warning: ERROR: View field icon collides with a variable or import file://app/src/main/res/layout/settings_widget_basic.xml Line:29
warning: ERROR: View field dialogMessage collides with a variable or import file://app/src/main/res/layout/voip_dialog_info.xml Line:33

> Task :app:compileReleaseKotlin FAILED
e: file://<...>/linphone-android/app/src/main/java/org/linphone/activities/voip/viewmodels/ConferenceViewModel.kt:542:13 Type mismatch: inferred type is Address? but Address was expected
e: file://<...>/src/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt:85:5 'showForegroundServiceNotification' overrides nothing
e: file://<...>/src/linphone-android/app/src/main/java/org/linphone/utils/LinphoneUtils.kt:97:21 Type mismatch: inferred type is Address? but Address was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

sdk was built from rev. 5459708b4c4b7db3ae544c4427587093698eeb6f, if that matters

**Comment by Viish** [comment]
Hi @lazydev2,

My bad, I gave you the wrong commit id. Try with `852e78c5a66debc515b3c7b88d3609c0b8b46ee7` (I just did it and it built just fine).

Cheers,

**Comment by lazydev2** [comment]
Thanks for help.
With rev 852e78c5a66debc515b3c7b88d3609c0b8b46ee7 it compiles and runs, but still no ICE fields in SIP Ok message

**Comment by harut420** [comment]
this is why also call-conference does not get any audio before cliccking on video button.

**Comment by lazydev2** [comment]
Its a pity that this promising project has gazzilion issues in the tracker, and no one tries to fix them.

However, for this particular bug I was able to track a cause.

It is linphone_call_new_incoming function from sdk.
It does not accept account in its parameters (as, for example, linphone_call_new_outgoing do), so the account information is not passed into instantiating Call object.

Which, in turn, cannot pass account into MediaSession::configure, which, in turn, cannot save ICE settings for later usage.

And later, when ICE settings are needed, they are not used, so ICE not works.

**Comment by vhbcet** [comment]
Sometimes we are in a hurry. I had the same problem and realized that I downloaded softphone-android-master from github. The file you need to download is linphone-android-master

**Comment by aftershow76** [comment]
I also have the same issue.  No ICE attributes on incoming call on Android.   There is no problem with IOS and Windows version as there are ICE attributes on incoming call. 

Also tested the latest Android version 6, but still no ICE attributes on incoming call.    Anyone got around this issue ?  

Thanks.



```
<--- Received SIP response (975 bytes) from TLS:202.124.144.x:1092 --->
SIP/2.0 200 Ok
Via: SIP/2.0/TLS 202.124.128.x:5061;rport;branch=z9hG4bKPjd3ea211b-77cc-4d71-907f-6496eb9eda6a;alias
From: "21852388" <sip:21852388@10.0.0.4>;tag=974dab2b-d47b-4a6e-aa77-0e970305d82e
To: <sip:10000@202.124.144.x>;tag=t6A8rox
Call-ID: 1a1f2c13-f0d7-4c85-93ec-10ed79a430c3
CSeq: 26026 INVITE
User-Agent: LinphoneAndroid/6.0.0 (A50) LinphoneSDK/5.4.0 (tags/5.4.0^0)
Supported: replaces, outbound, gruu, path, record-aware
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, PRACK, UPDATE
Contact: "10000" <sip:10000@202.124.144.x:1092;transport=tls>;+org.linphone.specs="lime"
Content-Type: application/sdp
Content-Length: 289

v=0
o=10000 1625 3609 IN IP4 192.168.1.14
s=Talk
c=IN IP4 192.168.1.14
t=0 0
m=audio 60047 RTP/SAVPF 107
a=rtpmap:107 opus/48000/2
a=fmtp:107 useinbandfec=1
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:QswIYBbH4lfZSXq25+PCoG0ghD3sb4AxlQkZfh2S
a=rtcp:39043
a=rtcp-fb:* trr-int 5000
```
